require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.autopairs"
spec "user.cmp"
spec "user.colorscheme"
spec "user.comment"
spec "user.devicons"
spec "user.lspconfig"
spec "user.lualine"
spec "user.mason"
spec "user.neotab"
spec "user.none-ls"
spec "user.nvimtree"
spec "user.oil"
-- spec "user.pandoc"
spec "user.telescope"
spec "user.treesitter"
spec "user.vim-pandoc"
spec "user.whichkey"

require "user.lazy"
